import { lazy } from "react";

export const LoginPage = lazy(() => import("../modules/auth/pages/LoginPage"))
export const AdminLayout = lazy(() => import("../layouts/AdminLayout"))
export const AdminPage = lazy(() => import("../modules/admin/pages/AdminPage"))
export const DoulaPage = lazy(() => import("../modules/doula/pages/DoulaPage"))
export const ClientPage = lazy(() => import("../modules/client/pages/ClientPage"))
export const PackagePage = lazy(() => import("../modules/doula/pages/PackagePage"))
export const DoulaViewPage = lazy(() => import("../modules/doula/pages/DoulaViewPage"))
export const ClientViewPage = lazy(() => import("../modules/client/pages/ClientViewPage"))
export const ArticlePage = lazy(() => import("../modules/article/pages/ArticlePage"))
export const PdSessionPage = lazy(() => import("../modules/pd-session/page/PdSessionPage"))
export const CategoryPage = lazy(() => import("../modules/category/page/CategoryPage"))
export const VoucherPage = lazy(() => import("../modules/voucher/pages/VoucherPage"))
export const VoucherViewPage = lazy(() => import("../modules/voucher/pages/VoucherViewPage"))
export const HelpDocumentPage = lazy(() => import("../modules/help-document/pages/HelpDocumentPage"))
export const SearchSettingPage = lazy(() => import("../modules/search-setting/page/SearchSettingPage"))
export const NotFoundPage = lazy(() => import("../modules/error/pages/NotFoundPage"))