export const mockBankAccounts = [
  {
    bankAccountUid: "cma-dbs-sgd",
    currency: "SGD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-SGD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "DBS BANK LTD",
    correspondentBankSwift: "DBSSSGSGXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - SGD",
  },
  {
    bankAccountUid: "cma-dbs-usd",
    currency: "USD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-USD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "JPMorgan Chase Bank, N.A.",
    correspondentBankSwift: "CHASUS33XXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - USD",
  },
  {
    bankAccountUid: "cma-dbs-hkd",
    currency: "HKD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-HKD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "DBS Bank (HK) Ltd",
    correspondentBankSwift: "DHBKHKHHXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - HKD",
  },
  {
    bankAccountUid: "cma-dbs-eur",
    currency: "EUR",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-EUR",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "Barclays Bank Ireland Frankfurt",
    correspondentBankSwift: "BARCDEFFXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - EUR",
  },
  {
    bankAccountUid: "float-dbs-sgd",
    currency: "SGD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – SGD (FLOAT)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-SGD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "DBS BANK LTD",
    correspondentBankSwift: "DBSSSGSGXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – SGD (FLOAT)",
  },
  {
    bankAccountUid: "float-dbs-usd",
    currency: "USD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – USD (FLOAT)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-USD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "JPMorgan Chase Bank, N.A.",
    correspondentBankSwift: "CHASUS33XXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – USD (FLOAT)",
  },
  {
    bankAccountUid: "float-dbs-hkd",
    currency: "HKD",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – HKD (FLOAT)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-HKD",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "DBS Bank (HK) Ltd",
    correspondentBankSwift: "DHBKHKHHXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – HKD (FLOAT)",
  },
  {
    bankAccountUid: "float-dbs-eur",
    currency: "EUR",
    beneficiaryName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – EUR (FLOAT)",
    beneficiaryBankName: "DBS Bank Ltd Singapore",
    beneficiaryBankAccountNumber: "XXXXXXX822-EUR",
    beneficiaryBankSwift: "DBSSSGSGXXX",
    correspondentBankName: "Barclays Bank Ireland Frankfurt",
    correspondentBankSwift: "BARCDEFFXXX",
    displayName: "SBI DIGITAL MARKETS PTE. LTD. – (CMA) – EUR (FLOAT)",
  },
];