export const mockListData = [
  {
    "id": 691,
    "parentId": null,
    "transactionId": "TXCSH0015889",
    "cashOrderNum": "CO-1ABC9HBXFEWPP",
    "couponOrderNum": null,
    "orderStatus": "pending",
    "orderStatusAlias": "pending",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "QB Official 85236",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker hi",
    "bankAccountUid": "cma-dbs-sgd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-SGD",
    "transactionType": "deposit",
    "transactionCategory": "credit",
    "createDo": "2026-02-03",
    "effectiveDo": "2026-02-03",
    "isin": "isin1234567890",
    "currency": "SGD",
    "description": "Initial deposit",
    "submitType": "admin-submit",
    "referenceNum": "DEP-20260203",
    "netAmt": 5000000,
    "feesAmt": 0,
    "gstAmt": 1000,
    "bankChargesAmt": 0,
    "cashOrderAmt": 5000000,
    "debit": null,
    "credit": 5000000,
    "files": null,
    "comments": "Approved by admin",
    "productOrderableType": null,
    "orderTransactionId": null,
    "bankAccountTxId": "DBS-TX-88901",
    "groupId": "GRP-APN-ADJ",
    "securityName": null,
    "payDt": "2026-02-03",
    "couponPaymentRate": null,
    "valueOfSettledHolding": null,
    "runningBal": 15000000,
    "postedTo": "Client",
    "couponPayments": null,
    "amount": 0,
    "totalCouponAmount": null,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 692,
    "parentId": null,
    "transactionId": "TXCSH0015890",
    "cashOrderNum": "CO-2WTH9HBXFEWPP",
    "couponOrderNum": null,
    "orderStatus": "complete",
    "orderStatusAlias": "complete",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "QQ Official 40263",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker hi",
    "bankAccountUid": "cma-dbs-sgd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-SGD",
    "transactionType": "withdrawal",
    "transactionCategory": "debit",
    "createDo": "2026-02-02",
    "effectiveDo": "2026-02-02",
    "isin": null,
    "currency": "EUR",
    "description": "Client withdrawal",
    "submitType": "client-submit",
    "referenceNum": "WTH-20260202",
    "netAmt": 2000000,
    "feesAmt": 50000,
    "gstAmt": 4004,
    "bankChargesAmt": 1000,
    "cashOrderAmt": 2000000,
    "debit": 2000064,
    "credit": null,
    "files": null,
    "comments": null,
    "productOrderableType": null,
    "orderTransactionId": null,
    "bankAccountTxId": "DBS-TX-88902",
    "groupId": null,
    "securityName": null,
    "payDt": "2026-02-02",
    "couponPaymentRate": null,
    "valueOfSettledHolding": null,
    "runningBal": 13000000,
    "postedTo": "Bank",
    "couponPayments": null,
    "amount": 0,
    "totalCouponAmount": null,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": "Nguyen Van A",
    "inBeneficiaryAccountNumber": "123-456-789",
    "needToReplaceFloatToCma": false
  },
  {
    "id": 693,
    "parentId": null,
    "transactionId": "TXCSH0015891",
    "cashOrderNum": null,
    "couponOrderNum": "CPN-0KJH98ABC",
    "orderStatus": "complete",
    "orderStatusAlias": "complete",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "QC Official 12345",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker",
    "bankAccountUid": "cma-dbs-sgd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-SGD",
    "transactionType": "credit",
    "transactionCategory": "credit",
    "createDo": "2026-02-01",
    "effectiveDo": "2026-02-01",
    "isin": "isin112233449988",
    "currency": "SGD",
    "description": "Coupon payment received",
    "submitType": "system-post",
    "referenceNum": "CPN-20260201",
    "netAmt": 350000,
    "feesAmt": 0,
    "gstAmt": 0,
    "bankChargesAmt": 0,
    "cashOrderAmt": null,
    "debit": null,
    "credit": 350000,
    "files": null,
    "comments": "Complete SBI DIGITAL MARKETS",
    "productOrderableType": "Bond",
    "orderTransactionId": "ORD-88991",
    "bankAccountTxId": "DBS-TX-88903",
    "groupId": "GRP-COUPON-01",
    "securityName": "SG GOV BOND 3Y",
    "payDt": "2026-02-01",
    "couponPaymentRate": 3.5,
    "valueOfSettledHolding": 10000000,
    "runningBal": 13350000,
    "postedTo": "Client",
    "couponPayments": null,
    "amount": 0,
    "totalCouponAmount": 350000,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 694,
    "parentId": null,
    "transactionId": "TXCSH0015892",
    "cashOrderNum": "CO-DEP-88992",
    "couponOrderNum": null,
    "orderStatus": "pending-maker",
    "orderStatusAlias": "pending",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "AB Official 45862",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker hi",
    "bankAccountUid": "cma-dbs-usd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA USD)",
    "bankAccountNum": "XXXXXXX901-USD",
    "transactionType": "deposit",
    "transactionCategory": "credit",
    "createDo": "2026-02-05",
    "effectiveDo": null,
    "isin": null,
    "currency": "USD",
    "description": "Client top-up",
    "submitType": "client-submit",
    "referenceNum": "DEP-USD-20260205",
    "netAmt": 2500000,
    "feesAmt": 0,
    "gstAmt": 0,
    "bankChargesAmt": 0,
    "cashOrderAmt": 2500000,
    "debit": null,
    "credit": 2500000,
    "files": null,
    "comments": "Waiting for checker approval",
    "productOrderableType": null,
    "orderTransactionId": null,
    "bankAccountTxId": null,
    "groupId": null,
    "securityName": null,
    "payDt": null,
    "couponPaymentRate": null,
    "valueOfSettledHolding": null,
    "runningBal": null,
    "postedTo": "Client",
    "couponPayments": null,
    "amount": 0,
    "totalCouponAmount": null,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 695,
    "parentId": 692,
    "transactionId": "TXCSH0015893",
    "cashOrderNum": "CO-FEE-88993",
    "couponOrderNum": null,
    "orderStatus": "draft",
    "orderStatusAlias": "draft",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "OO Official 36145",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker hi",
    "bankAccountUid": "cma-dbs-sgd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-SGD",
    "transactionType": "debit",
    "transactionCategory": "debit",
    "createDo": "2026-02-02",
    "effectiveDo": "2026-02-02",
    "isin": null,
    "currency": "SGD",
    "description": "Bank charge for withdrawal",
    "submitType": "system-post",
    "referenceNum": "FEE-20260202",
    "netAmt": 640000,
    "feesAmt": 50000,
    "gstAmt": 8000,
    "bankChargesAmt": 2500,
    "cashOrderAmt": null,
    "debit": 64510,
    "credit": null,
    "files": null,
    "comments": "approval at 2026-02-02",
    "productOrderableType": null,
    "orderTransactionId": null,
    "bankAccountTxId": "DBS-TX-88904",
    "groupId": "GRP-WTH-692",
    "securityName": null,
    "payDt": "2026-02-02",
    "couponPaymentRate": null,
    "valueOfSettledHolding": null,
    "runningBal": 12999936,
    "postedTo": "Bank",
    "amount": 0,
    "couponPayments": null,
    "totalCouponAmount": null,
    "parentTransactionId": "TXCSH0015890",
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 696,
    "parentId": null,
    "transactionId": "TXCSH0015894",
    "cashOrderNum": null,
    "couponOrderNum": "CPN-ADJ-88994",
    "orderStatus": "pending",
    "orderStatusAlias": "pending",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "SB Official 85236",
    "subOrgNum": "SRG-0FMC6Y4NE780H",
    "subOrgName": "QC for maker and checker hi",
    "bankAccountUid": "cma-dbs-sgd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-SGD",
    "transactionType": "coupon-payment",
    "transactionCategory": "coupon-payment",
    "createDo": "2026-01-31",
    "effectiveDo": "2026-01-31",
    "isin": "isin9988776655",
    "currency": "SGD",
    "description": "Coupon adjustment (rounding)",
    "submitType": "admin-adjust",
    "referenceNum": "CPN-ADJ-20260131",
    "netAmt": 5000,
    "feesAmt": 0,
    "gstAmt": 0,
    "bankChargesAmt": 0,
    "cashOrderAmt": null,
    "debit": null,
    "credit": 5000,
    "files": null,
    "comments": "Manual adjustment by admin",
    "productOrderableType": "Bond",
    "orderTransactionId": "ORD-88980",
    "bankAccountTxId": "DBS-TX-88905",
    "groupId": "CSF-QWB-HRD",
    "securityName": "CORP BOND 5Y",
    "payDt": "2026-01-31",
    "couponPaymentRate": null,
    "valueOfSettledHolding": 5000000,
    "runningBal": 13355000,
    "amount": 0,
    "postedTo": "Client",
    "couponPayments": null,
    "totalCouponAmount": 5000,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 697,
    "parentId": null,
    "transactionId": "TXCSH0049203",
    "cashOrderNum": null,
    "couponOrderNum": "VCX-RDA-11203",
    "orderStatus": "pending",
    "orderStatusAlias": "pending",
    "orgNum": "GG-0E1ZY1T99SS79",
    "orgName": "SB Official 20236",
    "subOrgNum": "SRG-0FMC6RAZOR80H",
    "subOrgName": "QC for maker",
    "bankAccountUid": "cma-dbs-usd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - USD",
    "bankAccountNum": "XXXXXXX822-USD",
    "transactionType": "credit",
    "transactionCategory": "credit",
    "createDo": "2026-03-31",
    "effectiveDo": "2026-03-31",
    "isin": "isin5106356581",
    "currency": "USD",
    "description": "Coupon adjustment (rounding)",
    "submitType": "admin-adjust",
    "referenceNum": "CPN-ADJ-20260331",
    "netAmt": 5000,
    "feesAmt": 50000,
    "gstAmt": 20500,
    "bankChargesAmt": 1000,
    "cashOrderAmt": null,
    "debit": 5000,
    "credit": 5000,
    "files": null,
    "comments": "Manual adjustment by admin",
    "productOrderableType": "Bond",
    "orderTransactionId": "ORD-88980",
    "bankAccountTxId": "DBS-TX-88905",
    "groupId": "QSA-CAF-GSA",
    "securityName": "CORP BOND 5Y",
    "payDt": "2026-03-31",
    "couponPaymentRate": null,
    "valueOfSettledHolding": 5000000,
    "runningBal": 13355000,
    "postedTo": "Client",
    "amount": 0,
    "couponPayments": null,
    "totalCouponAmount": 5000,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
  {
    "id": 698,
    "parentId": null,
    "transactionId": "TXYYS6845894",
    "cashOrderNum": null,
    "couponOrderNum": "CPN-YYY-012345",
    "orderStatus": "pending-maker",
    "orderStatusAlias": "pending-maker",
    "orgNum": "RG-0E1ZY1T9E8879",
    "orgName": "SBU OfficSial 501256",
    "subOrgNum": "SRG-0FLES80H",
    "subOrgName": "checker say hi",
    "bankAccountUid": "cma-dbs-usd",
    "bankAccountName": "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    "bankAccountNum": "XXXXXXX822-USD",
    "transactionType": "coupon-payment",
    "transactionCategory": "coupon-payment",
    "createDo": "2025-06-27",
    "effectiveDo": "2025-06-27",
    "isin": "isin9988776655",
    "currency": "SGD",
    "description": "Coupon adjustment (rounding)",
    "submitType": "admin-adjust",
    "referenceNum": "CPN-ADJ-20260131",
    "netAmt": 5000,
    "feesAmt": 0,
    "gstAmt": 0,
    "bankChargesAmt": 0,
    "cashOrderAmt": null,
    "debit": null,
    "credit": 5000,
    "files": null,
    "amount": 0,
    "comments": "Manual adjustment by admin",
    "productOrderableType": "Bond",
    "orderTransactionId": "ORD-88980",
    "bankAccountTxId": "DBS-TX-88905",
    "groupId": "AAA-OSP-ISD",
    "securityName": "CORP BOND 5Y",
    "payDt": "2025-06-27",
    "couponPaymentRate": null,
    "valueOfSettledHolding": 5000000,
    "runningBal": 13355000,
    "postedTo": "Client",
    "couponPayments": null,
    "totalCouponAmount": 5000,
    "parentTransactionId": null,
    "inBeneficiaryAccountName": null,
    "inBeneficiaryAccountNumber": null,
    "needToReplaceFloatToCma": false
  },
]

export const mockListDetail = [
  {
    cashOrderData: {
      transactionId: "TXCSH0015889",
      cashOrderNum: "CO-1ABC9HBXFEWPP",
      couponOrderNum: null,
      orderStatus: "pending",
      orderStatusAlias: "pending",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "QB Official 85236",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker hi",
      bankAccountUid: "cma-dbs-sgd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
      bankAccountNum: "XXXXXXX822-SGD",
      transactionType: "deposit",
      transactionCategory: "credit",
      createDo: "2026-02-03",
      effectiveDo: "2026-02-03",
      isin: "isin1234567890",
      currency: "SGD",
      description: "Initial deposit",
      submitType: "admin-submit",
      netAmt: 5000000,
      feesAmt: 0,
      gstAmt: 1000,
      bankChargesAmt: 0,
      debit: null,
      credit: 5000000,
      files: null,
      comments: "Approved by admin",
      productOrderableType: null,
      orderTransactionId: null,
      bankAccountTxId: "DBS-TX-88901",
      groupId: "GRP-APN-ADJ",
      securityName: null,
      payDt: "2026-02-03",
      couponPaymentRate: null,
      valueOfSettledHolding: null,
      runningBal: 15000000,
      postedTo: "Client",
      amount: 0,
      couponPayments: null,
      totalCouponAmount: null,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },

  {
    cashOrderData: {
      transactionId: "TXCSH0015890",
      cashOrderNum: "CO-2WTH9HBXFEWPP",
      couponOrderNum: null,
      orderStatus: "complete",
      orderStatusAlias: "complete",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "QQ Official 40263",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker hi",
      bankAccountUid: "cma-dbs-sgd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
      bankAccountNum: "XXXXXXX822-SGD",
      transactionType: "withdrawal",
      transactionCategory: "debit",
      createDo: "2026-02-02",
      effectiveDo: "2026-02-02",
      isin: null,
      currency: "EUR",
      description: "Client withdrawal",
      submitType: "client-submit",
      netAmt: 2000000,
      feesAmt: 50000,
      gstAmt: 4004,
      bankChargesAmt: 1000,
      debit: 2000064,
      credit: null,
      files: null,
      comments: null,
      productOrderableType: null,
      orderTransactionId: null,
      bankAccountTxId: "DBS-TX-88902",
      groupId: null,
      securityName: null,
      payDt: "2026-02-02",
      couponPaymentRate: null,
      valueOfSettledHolding: null,
      runningBal: 13000000,
      amount: 0,
      postedTo: "Bank",
      couponPayments: null,
      totalCouponAmount: null,
      parentTransactionId: null,
      inBeneficiaryAccountName: "Nguyen Van A",
      inBeneficiaryAccountNumber: "123-456-789"
    },
    pendingTaskData: null
  },

  {
    cashOrderData: {
      transactionId: "TXCSH0015891",
      cashOrderNum: null,
      couponOrderNum: "CPN-0KJH98ABC",
      orderStatus: "complete",
      orderStatusAlias: "complete",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "QC Official 12345",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker",
      bankAccountUid: "cma-dbs-sgd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
      bankAccountNum: "XXXXXXX822-SGD",
      transactionType: "credit",
      transactionCategory: "credit",
      createDo: "2026-02-01",
      effectiveDo: "2026-02-01",
      isin: "isin112233449988",
      currency: "SGD",
      description: "Coupon payment received",
      submitType: "system-post",
      netAmt: 350000,
      feesAmt: 0,
      gstAmt: 0,
      bankChargesAmt: 0,
      debit: null,
      credit: 350000,
      files: null,
      comments: "Complete SBI DIGITAL MARKETS",
      productOrderableType: "Bond",
      orderTransactionId: "ORD-88991",
      bankAccountTxId: "DBS-TX-88903",
      groupId: "GRP-COUPON-01",
      securityName: "SG GOV BOND 3Y",
      payDt: "2026-02-01",
      couponPaymentRate: 3.5,
      valueOfSettledHolding: 10000000,
      runningBal: 13350000,
      postedTo: "Client",
      amount: 0,
      couponPayments: null,
      totalCouponAmount: 350000,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },

  {
    cashOrderData: {
      transactionId: "TXCSH0015892",
      cashOrderNum: "CO-DEP-88992",
      couponOrderNum: null,
      orderStatus: "pending-maker",
      orderStatusAlias: "pending",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "AB Official 45862",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker hi",
      bankAccountUid: "cma-dbs-usd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA USD)",
      bankAccountNum: "XXXXXXX901-USD",
      transactionType: "deposit",
      transactionCategory: "credit",
      createDo: "2026-02-05",
      effectiveDo: "2026-02-05",
      isin: null,
      currency: "USD",
      description: "Client top-up QC for maker and checker hi and for bank detail SBI DIGITAL MARKETS PTE. LTD. - (CMA USD)",
      submitType: "client-submit",
      netAmt: 2500000,
      feesAmt: 0,
      gstAmt: 0,
      bankChargesAmt: 0,
      debit: null,
      credit: 2500000,
      files: null,
      comments: "Waiting for checker approval",
      productOrderableType: null,
      orderTransactionId: null,
      bankAccountTxId: null,
      groupId: null,
      securityName: null,
      payDt: null,
      couponPaymentRate: null,
      valueOfSettledHolding: null,
      runningBal: null,
      postedTo: "Client",
      amount: 0,
      couponPayments: null,
      totalCouponAmount: null,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },
  {
    cashOrderData: {
      transactionId: "TXCSH0015893",
      cashOrderNum: "CO-FEE-88993",
      couponOrderNum: null,
      orderStatus: "draft",
      orderStatusAlias: "draft",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "OO Official 36145",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker hi",
      bankAccountUid: "cma-dbs-sgd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
      bankAccountNum: "XXXXXXX822-SGD",
      transactionType: "debit",
      transactionCategory: "debit",
      createDo: "2026-02-02",
      effectiveDo: "2026-02-02",
      isin: null,
      currency: "SGD",
      description: "Bank charge for withdrawal",
      submitType: "system-post",
      netAmt: 640000,
      feesAmt: 50000,
      gstAmt: 8000,
      bankChargesAmt: 2500,
      debit: 64510,
      credit: null,
      files: null,
      comments: "approval at 2026-02-02",
      productOrderableType: null,
      orderTransactionId: null,
      bankAccountTxId: "DBS-TX-88904",
      groupId: "GRP-WTH-692",
      securityName: null,
      payDt: "2026-02-02",
      couponPaymentRate: null,
      valueOfSettledHolding: null,
      runningBal: 12999936,
      postedTo: "Bank",
      couponPayments: null,
      totalCouponAmount: 20000000,
      amount: 0,
      parentTransactionId: "TXCSH0015890",
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },
  {
    cashOrderData: {
      transactionId: "TXCSH0015894",
      cashOrderNum: null,
      couponOrderNum: "CPN-ADJ-88994",
      orderStatus: "pending",
      orderStatusAlias: "pending",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "SB Official 85236",
      subOrgNum: "SRG-0FMC6Y4NE780H",
      subOrgName: "QC for maker and checker hi",
      bankAccountUid: "cma-dbs-sgd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
      bankAccountNum: "XXXXXXX822-SGD",
      transactionType: "coupon-payment",
      transactionCategory: "coupon-payment",
      createDo: "2026-01-31",
      effectiveDo: "2026-01-31",
      isin: "isin9988776655",
      currency: "SGD",
      description: "Coupon adjustment (rounding)",
      submitType: "admin-adjust",
      netAmt: 5000,
      feesAmt: 0,
      gstAmt: 0,
      bankChargesAmt: 0,
      debit: null,
      credit: 5000,
      files: null,
      comments: "Manual adjustment by admin",
      productOrderableType: "Bond",
      orderTransactionId: "ORD-88980",
      bankAccountTxId: "DBS-TX-88905",
      groupId: "CSF-QWB-HRD",
      securityName: "CORP BOND 5Y",
      payDt: "2026-01-31",
      couponPaymentRate: null,
      valueOfSettledHolding: 5000000,
      runningBal: 13355000,
      postedTo: "Client",
      couponPayments: null,
      totalCouponAmount: 5000,
      amount: 0,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },
  {
    cashOrderData: {
      transactionId: "TXCSH0049203",
      cashOrderNum: null,
      couponOrderNum: "VCX-RDA-11203",
      orderStatus: "pending",
      orderStatusAlias: "pending",
      orgNum: "GG-0E1ZY1T99SS79",
      orgName: "SB Official 20236",
      subOrgNum: "SRG-0FMC6RAZOR80H",
      subOrgName: "QC for maker",
      bankAccountUid: "cma-dbs-usd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - USD",
      bankAccountNum: "XXXXXXX822-USD",
      transactionType: "credit",
      transactionCategory: "credit",
      createDo: "2026-03-31",
      effectiveDo: "2026-03-31",
      isin: "isin5106356581",
      currency: "USD",
      description: "Coupon adjustment (rounding)",
      submitType: "admin-adjust",
      netAmt: 5000,
      feesAmt: 50000,
      gstAmt: 20500,
      bankChargesAmt: 1000,
      debit: 5000,
      credit: 5000,
      files: null,
      comments: "Manual adjustment by admin",
      productOrderableType: "Bond",
      orderTransactionId: "ORD-88980",
      bankAccountTxId: "DBS-TX-88905",
      groupId: "QSA-CAF-GSA",
      securityName: "CORP BOND 5Y",
      payDt: "2026-03-31",
      couponPaymentRate: null,
      valueOfSettledHolding: 5000000,
      runningBal: 13355000,
      postedTo: "Client",
      amount: 0,
      couponPayments: null,
      totalCouponAmount: 5000,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  },
  {
    cashOrderData: {
      transactionId: "TXYYS6845894",
      cashOrderNum: null,
      couponOrderNum: "CPN-YYY-012345",
      orderStatus: "pending-maker",
      orderStatusAlias: "pending-maker",
      orgNum: "RG-0E1ZY1T9E8879",
      orgName: "SBU OfficSial 501256",
      subOrgNum: "SRG-0FLES80H",
      subOrgName: "checker say hi",
      bankAccountUid: "cma-dbs-usd",
      bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA) - USD",
      bankAccountNum: "XXXXXXX822-USD",
      transactionType: "coupon-payment",
      transactionCategory: "coupon-payment",
      createDo: "2025-06-27",
      effectiveDo: "2025-06-27",
      isin: "isin5106356581",
      currency: "USD",
      description: "Coupon adjustment (rounding)",
      submitType: "admin-adjust",
      netAmt: 5000,
      feesAmt: 50000,
      gstAmt: 20500,
      bankChargesAmt: 1000,
      debit: 5000,
      credit: 5000,
      files: null,
      comments: "Manual adjustment by admin",
      productOrderableType: "Bond",
      orderTransactionId: "ORD-88980",
      bankAccountTxId: "DBS-TX-88905",
      groupId: "AAA-OSP-ISD",
      securityName: "CORP BOND 5Y",
      payDt: "2025-06-27",
      couponPaymentRate: 10,
      valueOfSettledHolding: 5000000,
      runningBal: 13355000,
      amount: 0,
      postedTo: "Client",
      couponPayments: null,
      totalCouponAmount: 5000,
      parentTransactionId: null,
      inBeneficiaryAccountName: null,
      inBeneficiaryAccountNumber: null
    },
    pendingTaskData: null
  }
];
