export const countryCodes = [
  { code: "+93", label: "Afghanistan" },
  { code: "+355", label: "Albania" },
  { code: "+213", label: "Algeria" },
  { code: "+376", label: "Andorra" },
  { code: "+244", label: "Angola" },
  { code: "+54", label: "Argentina" },
  { code: "+374", label: "Armenia" },
  { code: "+61", label: "Australia" },
  { code: "+43", label: "Austria" },
  { code: "+994", label: "Azerbaijan" },

  { code: "+973", label: "Bahrain" },
  { code: "+880", label: "Bangladesh" },
  { code: "+375", label: "Belarus" },
  { code: "+32", label: "Belgium" },
  { code: "+501", label: "Belize" },
  { code: "+229", label: "Benin" },
  { code: "+975", label: "Bhutan" },
  { code: "+591", label: "Bolivia" },
  { code: "+387", label: "Bosnia and Herzegovina" },
  { code: "+267", label: "Botswana" },
  { code: "+55", label: "Brazil" },
  { code: "+673", label: "Brunei" },
  { code: "+359", label: "Bulgaria" },

  { code: "+855", label: "Cambodia" },
  { code: "+237", label: "Cameroon" },
  { code: "+1", label: "Canada" },
  { code: "+238", label: "Cape Verde" },
  { code: "+236", label: "Central African Republic" },
  { code: "+235", label: "Chad" },
  { code: "+56", label: "Chile" },
  { code: "+86", label: "China" },
  { code: "+57", label: "Colombia" },
  { code: "+269", label: "Comoros" },
  { code: "+506", label: "Costa Rica" },
  { code: "+385", label: "Croatia" },
  { code: "+53", label: "Cuba" },
  { code: "+357", label: "Cyprus" },
  { code: "+420", label: "Czech Republic" },

  { code: "+45", label: "Denmark" },
  { code: "+253", label: "Djibouti" },

  { code: "+593", label: "Ecuador" },
  { code: "+20", label: "Egypt" },
  { code: "+503", label: "El Salvador" },
  { code: "+240", label: "Equatorial Guinea" },
  { code: "+291", label: "Eritrea" },
  { code: "+372", label: "Estonia" },
  { code: "+251", label: "Ethiopia" },

  { code: "+358", label: "Finland" },
  { code: "+33", label: "France" },

  { code: "+995", label: "Georgia" },
  { code: "+49", label: "Germany" },
  { code: "+233", label: "Ghana" },
  { code: "+30", label: "Greece" },
  { code: "+502", label: "Guatemala" },

  { code: "+852", label: "Hong Kong" },
  { code: "+36", label: "Hungary" },

  { code: "+354", label: "Iceland" },
  { code: "+91", label: "India" },
  { code: "+62", label: "Indonesia" },
  { code: "+98", label: "Iran" },
  { code: "+964", label: "Iraq" },
  { code: "+353", label: "Ireland" },
  { code: "+972", label: "Israel" },
  { code: "+39", label: "Italy" },

  { code: "+81", label: "Japan" },
  { code: "+962", label: "Jordan" },

  { code: "+254", label: "Kenya" },
  { code: "+82", label: "Korea (South)" },
  { code: "+965", label: "Kuwait" },

  { code: "+856", label: "Laos" },
  { code: "+371", label: "Latvia" },
  { code: "+961", label: "Lebanon" },
  { code: "+370", label: "Lithuania" },
  { code: "+352", label: "Luxembourg" },

  { code: "+60", label: "Malaysia" },
  { code: "+960", label: "Maldives" },
  { code: "+223", label: "Mali" },
  { code: "+356", label: "Malta" },
  { code: "+52", label: "Mexico" },
  { code: "+976", label: "Mongolia" },
  { code: "+212", label: "Morocco" },
  { code: "+258", label: "Mozambique" },

  { code: "+95", label: "Myanmar" },

  { code: "+31", label: "Netherlands" },
  { code: "+234", label: "Nigeria" },
  { code: "+47", label: "Norway" },

  { code: "+92", label: "Pakistan" },
  { code: "+507", label: "Panama" },
  { code: "+63", label: "Philippines" },
  { code: "+48", label: "Poland" },
  { code: "+351", label: "Portugal" },

  { code: "+974", label: "Qatar" },

  { code: "+40", label: "Romania" },
  { code: "+7", label: "Russia" },

  { code: "+966", label: "Saudi Arabia" },
  { code: "+65", label: "Singapore" },
  { code: "+421", label: "Slovakia" },
  { code: "+386", label: "Slovenia" },
  { code: "+27", label: "South Africa" },
  { code: "+34", label: "Spain" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+46", label: "Sweden" },
  { code: "+41", label: "Switzerland" },

  { code: "+886", label: "Taiwan" },
  { code: "+66", label: "Thailand" },
  { code: "+216", label: "Tunisia" },
  { code: "+90", label: "Turkey" },

  { code: "+380", label: "Ukraine" },
  { code: "+971", label: "United Arab Emirates" },
  { code: "+44", label: "United Kingdom" },
  { code: "+64", label: "United States" },

  { code: "+598", label: "Uruguay" },
  { code: "+998", label: "Uzbekistan" },

  { code: "+58", label: "Venezuela" },
  { code: "+84", label: "Vietnam" },

  { code: "+967", label: "Yemen" },
  { code: "+263", label: "Zimbabwe" }
]
